library(lubridate)
hpc<-read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings = "?")
hpc1<-hpc[which(hpc$Date=="1/2/2007"|hpc$Date=="2/2/2007"),]
concat<-paste(hpc1$Date, hpc1$Time, sep=" ")
hpc1$datetime<-dmy_hms(concat)
hpc1$Global_active_power<-as.numeric(hpc1$Global_active_power)
dev.cur()
png("plot3.png",height=480, width=480)
plot(hpc1$datetime,hpc1$Sub_metering_1,type="l",xlab="",ylab="Energy Sub Metering",col="black")
lines(hpc1$datetime,hpc1$Sub_metering_2,type="l",col="red")
lines(hpc1$datetime,hpc1$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1, lwd=2)
dev.off()
